name: LogSwifty

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    name: Build & Test LogSwifty
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: "5.1"
    - name: View Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
